apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe.example.com-secret
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cafe-svc
          servicePort: 80
